export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const SIGNUP = 'SIGNUP';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const SET_PAGE = 'SET_PAGE';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const CHANGE_ARTICLES_LIST = 'CHANGE_ARTICLES_LIST';
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const ARTICLE_SUBMITTED = 'ARTICLE_SUBMITTED';
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR';
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';


export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const ARTICLE_LIKE = 'ARTICLE_LIKE';
export const ARTICLE_UNLIKE = 'ARTICLE_UNLIKE';

export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';









